#! /bin/sh

if [ ! $1 ] ; then
  echo "Specify a file name.";
  exit;
fi

fname="$1.tar";

src="src/*.c include/*.h bskrun.c bskcompile.c bsktreasure.c bskcallbacks.c bskcallbacks.h Makefile* README LICENSE CHANGELOG treasure.ini config.h";
doc="docs/*";
dat="dat/dragon/*.bsk dat/scitadel/*.bsk dat/snfist/*.bsk dat/standard/*.bsk dat/nbomt/*.bsk dat/tnblood/*.bsk dat/boem/*.bsk dat/defenders/*.bsk dat/diablo/*.bsk dat/dungeon/*.bsk dat/motp/*.bsk dat/polyhedron/*.bsk dat/frcs/*.bsk dat/mof/*.bsk dat/rr/*.bsk dat/DLofM/*.bsk dat/demonology/*.bsk dat/SongSil/*.bsk dat/LoD/*.bsk dat/MonstersofF/*.bsk dat/TrapsTreach/*.bsk dat/Undead/*.bsk dat/Gladiator/*.bsk dat/Dragons/*.bsk dat/NDreams/*.bsk dat/Evil/*.bsk dat/MysticWar/*.bsk dat/Dungeons/*.bsk dat/Necromancy/*.bsk dat/TbtGods/*.bsk dat/Diomin/*.bsk dat/LoH/*.bsk dat/Jade/*.bsk"

case $2 in
  "")
    echo Please specify 'src', 'all', 'doc', or 'data'.;
    exit ;;
  "src")
    data="$src" ;;
  "all")
    data="$src $doc $dat" ;;
  "doc")
    data="$doc" ;;
  "data")
    data="$dat" ;;
esac

if [ "$3" = "zip" ] ; then
  fname="$1.zip";
  zip $fname $data;
else
  tar cvf $fname $data;
  gzip --best -fq $fname;
fi
